Issue #21: Added contract creation details to contract summary
cibr-qcri/kansa pull request #23
Opened 2022-09-01 09:48 UTC by thedarkspy

Closes #21

2022-09-01 09:50 UTC, thedarkspy commented
I suggest adding contract type at a later stage when we decide what to label ERC20 and ERC721 contracts. Currently true or false values do not add much to the context. Moreover, since they are not always available, this might miss the even number of summary fields we have. We can also add them as checkboxes that are ticked whenever a value is true.

2022-09-04 06:40 UTC, thedarkspy commented
![Screen Shot 2022-09-04 at 9 39 02 AM](https://user-images.githubusercontent.com/10672009/188300906-3bda50d8-284e-4d8d-bebc-2e0047120560.png)

2022-09-04 08:01 UTC, thedarkspy commented
![Screen Shot 2022-09-04 at 11 00 32 AM](https://user-images.githubusercontent.com/10672009/188303636-0f371393-b42f-4f7b-a8e2-2546e5003b29.png)

Updated UI

2022-09-04 09:47 UTC, boshmaf requested changes

2022-09-04 09:47 UTC, boshmaf commented on api/controllers/contracts.js
> +  console.log(result.rows);
Please remove

2022-09-04 09:47 UTC, boshmaf commented on api/utils/contracts.js
> +    id: row.id,
Use JS case styles for naming: camelCase

2022-09-04 09:47 UTC, boshmaf commented on web/src/components/Contract/Summary/Summary.js
> +  total_received: 'Total In',
Please use camelCase for names

2022-09-04 10:45 UTC, boshmaf approved these changes

2022-09-04 10:45 UTC, merged