Issue #22: Implemented vulnerabilities tab and redesigned the app tabs
cibr-qcri/kansa pull request #28
Opened 2022-09-16 14:10 UTC by thedarkspy

Closes #22

2022-09-16 15:29 UTC, boshmaf requested changes

2022-09-16 15:29 UTC, boshmaf commented on web/src/components/Contract/Tabs/Reports/Reports.js
> +      text = 'The contract was not scanned by this scanner yet.';
`The contract has not been analyzed by this scanner yet.`

Grammer + different verb.

2022-09-16 15:29 UTC, boshmaf commented on web/src/components/Contract/Tabs/Vulnerabilities/Vulnerabilities-styles.js
> +      padding: 16,
Please use theme.spacing instead for paddings and margins.

2022-09-16 15:29 UTC, boshmaf commented on web/src/components/Contract/Tabs/Vulnerabilities/Vulnerabilities.js
> +    </TableContainer>
Please use [DataTableRaw](https://github.com/cibr-qcri/kansa/tree/main/web/src/components/DataTableRaw) component instead. Also, please make sure you're using this *for all Tabs that show data tables.* This raw component handles pagination, empty results, etc.

2022-09-18 08:00 UTC, thedarkspy commented on web/src/components/Contract/Tabs/Vulnerabilities/Vulnerabilities-styles.js
> +      padding: 16,
Addressed

2022-09-18 09:34 UTC, boshmaf approved these changes

2022-09-18 09:40 UTC, merged